In [61]:
!pip install selenium
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

Requirement already satisfied: selenium in c:\users\dell\anaconda3\lib\site-packages (4.4.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: certifi~=2021.10.8 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio~=0.17 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (0.21.0)
Requirement already satisfied: sniffio in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: cffi>=1.14 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: sortedcontainers in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: attrs>=19.2.0 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\dell\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)

In [62]:
# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
driver = webdriver.Chrome(r'C:\Users\DELL\Downloads\chromedriver_win32\Chromedriver.exe')
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [74]:
Name=[]

Titles=driver.find_elements(By.XPATH,'//*[@id="mw-content-text"]/div[1]/table[2]/tbody/tr')
for i in Titles:
    title=i.text
    Name.append(title)

In [77]:
df=pd.DataFrame({'Details':Name})
df

                                              Details
0   1. "Baby Shark Dance"[3] Pinkfong Baby Shark -...
1   2. "Despacito"[6] Luis Fonsi 7.97 January 12, ...
2   3. "Johny Johny Yes Papa"[12] LooLoo Kids 6.45...
3   4. "Shape of You"[13] Ed Sheeran 5.80 January ...
4   5. "See You Again"[15] Wiz Khalifa 5.63 April ...
5   6. "Bath Song"[20] Cocomelon – Nursery Rhymes ...
6   7. "Phonics Song with Two Words"[21] ChuChu TV...
7   8. "Uptown Funk"[22] Mark Ronson 4.68 November...
8   9. "Learning Colors – Colorful Eggs on a Farm"...
9   10. "Gangnam Style"[24] Psy 4.54 July 15, 2012...
10  11. "Masha and the Bear – Recipe for Disaster"...
11  12. "Wheels on the Bus"[30] Cocomelon – Nurser...
12  13. "Dame Tu Cosita"[31] El Chombo 4.06 April ...
13     14. "Sugar"[32] Maroon 5 3.75 January 14, 2015
14   15. "Roar"[33] Katy Perry 3.65 September 5, 2013
15  16. "Counting Stars"[34] OneRepublic 3.64 May ...
16  17. "Sorry"[35] Justin Bieber 3.58 October 22,...
17     18. "Axel F"[36] Crazy Frog 3.50 June 16, 2009
18  18. "Thinking Out Loud"[37] Ed Sheeran 3.49 Oc...
19  20. "Baa Baa Black Sheep"[38] Cocomelon – Nurs...
20  21. "Dark Horse"[39] Katy Perry 3.34 February ...
21  22. "Faded"[40] Alan Walker 3.34 December 3, 2015
22  23. "Girls Like You"[41] Maroon 5 3.33 May 31,...
23  24. "Let Her Go"[42] Passenger 3.29 July 25, 2012
24  25. "Bailando"[43] Enrique Iglesias 3.26 April...
25  26. "Lean On"[44] Major Lazer 3.26 March 22, 2015
26  27. "Perfect"[45] Ed Sheeran 3.25 November 9, ...
27  28. "Waka Waka (This Time for Africa)"[46] Sha...
28  29. "Shake It Off"[47] Taylor Swift 3.20 Augus...
29  30. "Humpty the train on a fruits ride"[48] Ki...

I had to scrape it like this because there were no classes to scrape from and when xpath was used on the element i couldnt iterate and get every value in table(due to similar paths)

In [79]:
# 2. Scrape the details team India’s international fixtures from bcci.tv

driver = webdriver.Chrome(r'C:\Users\DELL\Downloads\chromedriver_win32\Chromedriver.exe')
driver.get('https://www.bcci.tv/')

In [80]:
International=driver.find_element(By.XPATH,"/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
International.click()

In [86]:
Series=[]
Titles=[]
Location=[]
Dates=[]
Time=[]

Ser=driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
for i in Ser:
    siri=i.text
    Series.append(siri)

Title=driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
for i in Title:
    tit=i.text
    Titles.append(tit)
    
Locations=driver.find_elements(By.XPATH,'//div[@class="fix-place ng-binding ng-scope"]')
for i in Locations:
    loc=i.text.split("-")[1]
    Location.append(loc)
    
Date=driver.find_elements(By.XPATH,'//div[@class="match-card-left match-schedule"]')
for i in Date:
    D=i.text
    Dates.append(D)

times=driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
for i in times:
    T=i.text
    Time.append(T)

In [88]:
df=pd.DataFrame({'Series':Series,'Titles':Titles,'Location':Location,'Dates':Dates,'Time':Time})
df

,Series,Titles,Location,Dates,Time
0,INDIA WOMEN TOUR OF ENGLAND T20 SERIES 2022,3rd T20I -,"County Ground, Bristol",15 SEP 2022,11:00 PM IST
1,INDIA WOMEN TOUR OF ENGLAND ODI SERIES 2022,1st ODI -,"County Ground, Hove",18 SEP 2022,3:30 PM IST
2,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,1st T20I -,"Punjab Cricket Association IS Bindra Stadium,...",20 SEP 2022,7:30 PM IST
3,INDIA WOMEN TOUR OF ENGLAND ODI SERIES 2022,2nd ODI -,"St Lawrence Ground, Canterbury",21 SEP 2022,5:30 PM IST
4,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,2nd T20I -,"Vidarbha Cricket Association Stadium, Nagpur",23 SEP 2022,7:30 PM IST
5,INDIA WOMEN TOUR OF ENGLAND ODI SERIES 2022,3rd ODI -,"Lord's Cricket Ground, London",24 SEP 2022,3:30 PM IST
6,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,3rd T20I -,"Rajiv Gandhi International Stadium, Hyderabad",25 SEP 2022,7:30 PM IST
7,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022-23,1st T20I -,"Greenfield International Stadium, Thiruvanant...",28 SEP 2022,7:30 PM IST

In [89]:
# 3. Scrape the details of selenium exception from guru99.com

driver = webdriver.Chrome(r'C:\Users\DELL\Downloads\chromedriver_win32\Chromedriver.exe')
driver.get('https://www.guru99.com/')

In [90]:
# 4. Scrape the details of State-wise GDP of India from statisticstime.com.

driver = webdriver.Chrome(r'C:\Users\DELL\Downloads\chromedriver_win32\Chromedriver.exe')
driver.get('http://statisticstimes.com/')

In [91]:
# 5. Scrape the details of trending repositories on Github.com.

driver = webdriver.Chrome(r'C:\Users\DELL\Downloads\chromedriver_win32\Chromedriver.exe')
driver.get('https://github.com/')

In [96]:
Open=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
Open.click()

Tr=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
Tr.click()

In [106]:
Title=[]
Description=[]
Contributors=[]
Language=[]

Titles=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]')
for i in Titles[:10]:
    tit=i.text
    Title.append(tit)

Desc=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for i in Desc[:10]:
    D=i.text
    Description.append(D)
    
Contr=driver.find_elements(By.XPATH,'//a[@class="Link--muted d-inline-block mr-3"]')
for i in Contr[:10]:
    count=i.text
    Contributors.append(count)

Lang=driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]')
for i in Lang[:10]:
    lan=i.text
    Language.append(lan)
    
df=pd.DataFrame({'Title':Title,'Description':Description,'Contributors':Contributors,'Language':Language})
df

,Title,Description,Contributors,Language
0,pocketbase / pocketbase,Open Source realtime backend in 1 file,"12,373",Go
1,alura / techguide,TechGuide main repository with the code that g...,396,TypeScript
2,danielgindi / Charts,Beautiful charts for iOS/tvOS/OSX! The Apple s...,535,Swift
3,ethereum / ethereum-org-website,Ethereum.org is a primary online resource for ...,32,Markdown
4,revanced / revanced-manager,💊 The official ReVanced Manager,"25,926",Dart
5,remix-run / react-router,Declarative routing for React,"5,490",TypeScript
6,PaddlePaddle / PaddleHub,Awesome pre-trained models toolkit based on Pa...,"3,151",Python
7,malwaredllc / byob,An open-source post-exploitation framework for...,"3,106",Python
8,surrealdb / surrealdb,"A scalable, distributed, collaborative, docume...","1,536",Rust
9,ascoders / weekly,前端精读周刊。帮你理解最前沿、实用的技术。,275,JavaScript

In [107]:
# 6. Scrape the details of top 100 songs on billiboard.com.

driver = webdriver.Chrome(r'C:\Users\DELL\Downloads\chromedriver_win32\Chromedriver.exe')
driver.get('https:/www.billboard.com/')

In [109]:
Charts=driver.find_element(By.XPATH,'/html/body/div[3]/div[7]/div/div/div/ul/li[1]/h3/button')
Charts.click()

Hot=driver.find_element(By.XPATH,'/html/body/div[3]/div[7]/div/div/div/ul/li[1]/ul/li[2]/a')
Hot.click()

In [122]:
Details=[]

Titles=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]')
for i in Titles[:100]:
    tit=i.text.split("/n")
    Details.append(tit)

    
df=pd.DataFrame({'Details':Details})
df

                                              Details
0                 [As It Was\nHarry Styles\n1\n1\n23]
1                   [Bad Habit\nSteve Lacy\n2\n2\n10]
2       [Late Night Talking\nHarry Styles\n12\n3\n16]
3             [Sunroof\nNicky Youre & dazy\n5\n4\n15]
4                  [About Damn Time\nLizzo\n3\n1\n21]
..                                                ...
95  [Thought You Should Know\nMorgan Wallen\n96\n1...
96                 [Country On\nLuke Bryan\n-\n76\n3]
97                     [Static\nSteve Lacy\n-\n98\n1]
98           [Billie Eilish.\nArmani White\n-\n99\n1]
99  [Sin Fin\nRomeo Santos & Justin Timberlake\n-\...

[100 rows x 1 columns]

In [113]:
print(len(Title),len(Description),len(Contributors),len(Language))

1 0 0 0